services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_app  # <--- Esta línea debe tener 4 espacios de indentación
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_PROTOCOL: 'https'
      VUE_APP_URL_BASE: 'https://n8n.mariomojica.com/' # Usando HTTPS
      N8N_HOST: 'n8n.mariomojica.com' # Si aplica
      N8N_ENCRYPTION_KEY: 'dQ1BaVIoERmzJt3dXMAKld3O7kfB/QCGlmc8EYr3'
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_SECURE_COOKIE: 'false'
    volumes:
      - /opt/n8n/data:/home/node/.n8n

  # -----------------------------------------------------------------
  # SERVICIO 2: NGINX PROXY MANAGER (Proxy Inverso con SSL)
  # -----------------------------------------------------------------
  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm_proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "db_npm"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm_user"
      # CRÍTICO 3: PEGA AQUÍ EL RESULTADO DE la CLAVE 3 (Contraseña MySQL)
      DB_MYSQL_PASSWORD: 'F5GqcxxtB9ef8TkMLnoK6Lo8PQgRLvtxAIgHBx6Q'
      DB_MYSQL_NAME: "npm_db"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - db_npm

  # -----------------------------------------------------------------
  # SERVICIO 3: BASE DE DATOS para Nginx Proxy Manager (MariaDB)
  # -----------------------------------------------------------------
  db_npm:
    image: mariadb:10.9
    container_name: npm_database
    restart: unless-stopped
    environment:
      # CRÍTICO 4: PEGA AQUÍ EL RESULTADO DE la CLAVE 3 (Contraseña MySQL)
      MYSQL_ROOT_PASSWORD: 'GqcxxtB9eF5f8TkMLnoK6Lo8PQgRLvtxAIgHBx6Q'
      MYSQL_DATABASE: "npm_db"
      MYSQL_USER: "npm_user"
      # CRÍTICO 5: PEGA AQUÍ EL RESULTADO DE la CLAVE 3 (Contraseña MySQL)
      MYSQL_PASSWORD: 'F5GqcxxtB9ef8TkMLnoK6Lo8PQgRLvtxAIgHBx6Q'
    volumes:
      - ./npm/mysql:/var/lib/mysql

networks:
  default:
    name: internal_network
