[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://dezaisaunoumhqpssols.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_HyhWSanS2mhByF476p_EzA_6oq2bQOT"

